# fly.toml app configuration file generated for backend-integrador on 2023-11-30T09:04:37-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-integrador"
primary_region = "eze"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
